Final sprint on Feature-Sliced Design
ClevertecFrontendLab/alterrant pull request #5
Opened 2023-03-26 12:54 UTC by alterrant

Спритны выполнены на архитектуре Feature-Sliced Design(FSD). Документация описана в на сайте у разработчиков Feature-Sliced Design, есть на русском)

Файловую структуру читать так: shared(вообще без bll логики, всё переиспользуемое) => entities => features => widgets => pages => processes => app. Импорты в свой и предыдущие слои запрещены. Исключение -- layouts в widgets - в них можно импортировать из widgets. 

Стор находится у компонентах в entities/features. Сущности разделены в основном по bll логике.

Апи находится в shared

2023-03-26 13:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679835973/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 13:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679837811/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-26 15:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679844881/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-26 16:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679847574/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-26 18:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 90%.
Общее количество тестов: 98.
Количество непройденных тестов: 9.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20validation%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error forgot password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20forgot%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- reset password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20reset%20password%20validation%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- registration -- validation first step (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%205%20--%20authorization%20and%20registartion%20--%20registration%20--%20validation%20first%20step%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679853853/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-26 19:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679860542/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 20:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679863670/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)

2023-03-26 21:00 UTC, alterrant commented
Спритны выполнены на архитектуре Feature-Sliced Design(FSD). Документация описана в на сайте у разработчиков Feature-Sliced Design, есть на русском)

Файловую структуру читать так: shared(вообще без bll логики, всё переиспользуемое) => entities => features => widgets => pages => processes => app. Импорты в свой и предыдущие слои запрещены. Исключение -- layouts в widgets - в них можно импортировать из widgets.

Стор находится у компонентах в entities/features. Сущности разделены в основном по bll логике.

Апи находится в shared

2023-03-26 22:33 UTC, SergeyGlazun requested changes

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
>  trim_trailing_whitespace = true
![image](https://user-images.githubusercontent.com/70904466/227807820-1870d24e-4dbe-4f3a-bb80-6d10f26d9a5f.png)
при не правильной валидации летит запрос

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
>  trim_trailing_whitespace = true
![image](https://user-images.githubusercontent.com/70904466/227807855-5b9ab9b9-8c32-4ccf-94ae-7dfc2f32dc30.png)

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
>  max_line_length = 100
![image](https://user-images.githubusercontent.com/70904466/227808048-2331d523-b3a4-4fbc-889c-233e57f23d29.png)
данные изменены на валидные кнопка заблочена

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
>  indent_style = space
![image](https://user-images.githubusercontent.com/70904466/227808132-33d4e4f8-5e90-423e-971f-6ae389fbf3cf.png)
нет лодера

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
> -indent_size = 4
![image](https://user-images.githubusercontent.com/70904466/227808167-c90acf0b-4030-472f-93a4-3f6917d7f6ae.png)
скролл

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
> +indent_size = 2
![image](https://user-images.githubusercontent.com/70904466/227808280-66b1db0d-4071-4b09-a75f-4222c3afadd3.png)
не по макету

2023-03-26 22:33 UTC, SergeyGlazun commented on .editorconfig
>  [package.json]
![image](https://user-images.githubusercontent.com/70904466/227808293-9e02693f-2410-4e3b-b512-f2938cae9905.png)
юай кит вроде не нет такого цвета

2023-03-26 22:33 UTC, SergeyGlazun commented on cypress.config.ts
![image](https://user-images.githubusercontent.com/70904466/227808412-afc237eb-2e16-48a7-ba3a-80008ffd8c7e.png)

2023-03-26 22:33 UTC, SergeyGlazun commented on cypress.config.ts
>  export default defineConfig({
![image](https://user-images.githubusercontent.com/70904466/227808447-9f59a1f4-de4f-4d9a-8bae-37ede30433bd.png)
по макету там котик стоит

2023-03-26 22:33 UTC, SergeyGlazun commented on cypress.config.ts
>      e2e: {
![image](https://user-images.githubusercontent.com/70904466/227808534-416f837e-7bd0-4af7-969e-fb9c0a1e4ec4.png)
бургер остался в дестоп версии

2023-03-26 22:33 UTC, SergeyGlazun commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/70904466/227808579-422698ac-5c26-4029-ae06-6f8e8e361b20.png)

2023-03-26 22:33 UTC, SergeyGlazun commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
![image](https://user-images.githubusercontent.com/70904466/227808619-527481e3-f225-4fb1-81a7-ed04768a44e0.png)
на мобилке эта штука вроде вытягивается и крестик должен быть когда вводиться инфа

2023-03-26 22:33 UTC, SergeyGlazun commented on src/app/index.css
>    padding:0;
![image](https://user-images.githubusercontent.com/70904466/227808725-f9a64366-e7db-46b5-a9e8-870297f9c934.png)
а де лодер

2023-03-26 22:33 UTC, SergeyGlazun commented on src/app/index.css
>  }
![image](https://user-images.githubusercontent.com/70904466/227808774-25ce7241-b65e-450c-8b55-bc179abda3b5.png)
забронировал книгу а бронь уже истекла сразу

2023-03-26 22:33 UTC, SergeyGlazun commented on src/app/index.css
> +  width:7px;
![image](https://user-images.githubusercontent.com/70904466/227808863-dbaca17f-9a67-4938-97bf-adb6f3c0f9e2.png)
отменяю бронь ничего ен происходит

2023-03-27 00:52 UTC, alterrant commented on src/shared/ui/stars/index.tsx
> +  const isInvertStars = isHover;
Работать будет, но снаружи компоненты нам нужно знать, что isHover - это свойство, которое отвечает за включение ховера, а внутри компоненты нужно знать, что это включение инверсии блока со звёздами. Исправил так: переопределил переменную при деструктуризации

2023-03-27 02:32 UTC, alterrant commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
"В мобильной версии при нажатии на кнопку открытия поисковой панели должна открываться поисковая панель, при этом если мы введем какое-то значение в инпут и нажмем на крестик, тем самым свернем поисковую панель, то значение, которое мы вводили, должно сохраниться и при повторном открытии поисковой панели мы должны там увидеть значение, которое мы вводили." 
(спринт 4, https://docs.google.com/document/d/1vgj_EIHl5IvVqNaPZChI07kBtkbLKaBh/edit)

На макете мобильная версия - это 320px. На мобильной версии, если нажать на иконку, то развернётся поле ввода, появляется крестик, когда вводим значение.

Логику разворачивания поля ввода для не мобильных версий сохранил по нажатию на иконку лупы. С 768px до 320px при изменении разрешении экрана интерактивно уменьшается размер поля ввода, пока не дойдёт до мобильного разрешения, т.е. 320px (выглядит так: поле ввода плавно сжимается до инконки). Развернуть поле ввода можно на любой версии, нажав на значок поиска. Это не описывалось в тз, но мне показалось, это из него следует, по крайней мере не запрещалось)

2023-03-27 06:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- error reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alterrant/1679899974/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20error%20reset%20password%20(failed).png)

2023-03-27 07:24 UTC, SergeyGlazun approved these changes

2023-03-27 09:29 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:58 UTC, merged